language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libltdl
    - libltdl-dev
  
script:
  - ls /usr/lib/libltdl*
  - ls /usr/lib/libcurl*
  - ls /usr/lib/libjs*
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - sudo make install

#script: ./autogen.sh && ./configure && make 
