language: c
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libltdl7
    - libltdl-dev
    - libtool
    - libjson0
    - libjson0-dev

#install:
#  - libtoolize -c
#  - cd libltdl
#  - ./configure
#  - make && make install

script:
  - ls /usr/lib64
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make install

#script: ./autogen.sh && ./configure && make
