language: c
sudo: false
os: 
  - linux
  - osx

cache:
  directories: 
    - $HOME/jsonc_linux
    - $HOME/jsonc_osx 

compiler:
  - gcc
  - clang

install:
  - sh ./install_jsonc_$TRAVIS_OS_NAME.sh
  - sh ./install_libuv_$TRAVIS_OS_NAME.sh  

script:
  - ls -r $HOME/jsonc_$TRAVIS_OS_NAME
  - export INCLUDE="$HOME/jsonc/include"
  - export LIB="$HOME/jsonc/lib"
  - export CFLAGS="$CFLAGS -fPIC"
  - mkdir -p build
  - cd build
  - cmake ..
  - make

#script: ./autogen.sh && ./configure && make
