language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -y libjson-c-dev libcurl4-gnutls-dev libltdl-dev
  
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - sudo make install

#script: ./autogen.sh && ./configure && make 
