language: c

sudo: false

cache:
  directories: $HOME/jsonc

compiler:
  - gcc
  - clang

install:
  - sh ./install_jsonc.sh

script:
  - ls -r $HOME/jsonc
  - export INCLUDE="$HOME/jsonc/include"
  - export LIB="$HOME/jsonc/lib"
  - export CFLAGS="-L$HOME/jsonc/lib -I$HOME/jsonc/include"
  - mkdir -p build
  - cd build
  - cmake ..
  - make

#script: ./autogen.sh && ./configure && make
