language: c

sudo: false

cache:
  directories: 
    - $HOME/jsonc
    - $HOME/pcc

compiler:
  - gcc
  - clang
  - pcc

env:
  - PATH="$HOME/pcc/bin:$PATH" CFLAGS="-L$HOME/pcc/lib" LD_LIBRARY_PATH="$HOME/pcc/lib"

install:
  - sh ./install_jsonc.sh
  - sh ./install_pcc.sh

script:
  - ls -r $HOME/jsonc
  - export INCLUDE="$HOME/jsonc/include"
  - export LIB="$HOME/jsonc/lib"
  - export CFLAGS="$CFLAGS -fPIC"
  - mkdir -p build
  - cd build
  - cmake ..
  - make

#script: ./autogen.sh && ./configure && make
