language: c
sudo: false
os: 
  - linux
  - osx  

cache:
  directories: $HOME/jsonc

compiler:
  - gcc
  - clang

before_install:
  - brew update
  - brew outdated libuv || brew upgrade libuv

install:
  - sh ./install_jsonc_$TRAVIS_OS_NAME.sh

script:
  - ls -r $HOME/jsonc
  - export INCLUDE="$HOME/jsonc/include"
  - export LIB="$HOME/jsonc/lib"
  - export CFLAGS="$CFLAGS -fPIC"
  - mkdir -p build
  - cd build
  - cmake ..
  - make

#script: ./autogen.sh && ./configure && make
