language: c
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libltdl-dev
    - libtool
    - libjson-c-dev
    - libjson-c2

install:
  - libtoolize -c
  - cd libltdl
  - ./configure
  - make && make install

script:
  - ls /usr/lib64
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make install

#script: ./autogen.sh && ./configure && make
