language: c
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libltdl-dev
    - libjson0-dev

install:
  - wget https://github.com/json-c/json-c/archive/json-c-0.12-20140410.tar.gz
  - tar -xzvf json-c-0.12-20140410.tar.gz
  - cd json-c-json-c-0.12-20140410
  - ./configure
  - CC="-Wno-error=unused-but-set-variable" make
  - make install

script:
  - ls /usr/lib/*-linux-gnu
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make install

#script: ./autogen.sh && ./configure && make
